CREATE TABLE SEQUENCEORG (
    EMPNO VARCHAR(12),
    SPOSCODE VARCHAR(3),
    CCO CHAR(1),
    HEADNO VARCHAR(12),
    SPOSCODE1 VARCHAR(3),
    CCO1 CHAR(1),
    VORGNO VARCHAR(6),
    VORGNO1 VARCHAR(6)
);
