import { VARCHAR } from 'ibm_db';
import { Column, Entity, ManyToMany, PrimaryGeneratedColumn } from 'typeorm';

@Entity({ name: 'STOCK_MOVEMENT_ITEMS', schema: 'PURSYS' })
export class StockMovementItems {
    @PrimaryGeneratedColumn()
    ITEM_ID: number;

    @Column()
    MOVEMENT_ID: number;

    @Column()
    PRODUCT_ID: number;

    @Column()
    LOT_ID: number;

    @Column()
    QUANTITY: number;

    @Column()
    UNIT_COST: number;

    @Column()
    REMARK: string;
}

/*
CREATE TABLE STOCK_TRANSACTION_ITEMS (
    ID	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PROD_ID	NUMBER,
    LOT_ID	NUMBER,
    TRN_ID	NUMBER,
    TRN_QTY	NUMBER,
    UNIT_COST	NUMBER,
    REMARK	VARCHAR2(200)
);
*/
