import { Column, Entity, ManyToMany, PrimaryGeneratedColumn } from 'typeorm';

@Entity({ name: 'STOCK_MOVEMENTS', schema: 'PURSYS' })
export class StockMovements {
    @PrimaryGeneratedColumn()
    MOVEMENT_ID: number;

    @Column()
    DOCUMENT_NO: string;

    @Column()
    MOVEMENT_TYPE: string;

    @Column()
    SOURCE_STORAGE: number;

    @Column()
    DEST_STORAGE: number;

    @Column()
    STATUS: string;

    @Column()
    CREATED_AT: Date;

    @Column()
    CREATED_BY: string;
}
/*

CREATE TABLE STOCK_TRANSACTIONS(
ID	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
DOCUMENT_NO	VARCHAR2(50) NOT NULL,
TRNTYPE	VARCHAR2(1) NOT NULL,
STORAGE_FROM	NUMBER,
STORAGE_TO	NUMBER,
CSTATUS	VARCHAR2(1) NOT NULL,
CREATED_AT	TIMESTAMP(6) NOT NULL,
CREATED_BY	VARCHAR2(10) NOT NULL
);

*/
