CREATE TABLE "DOCUMENT_MSTLST"
   (	"DIVCODE" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"PROTID" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"PROMID" NUMBER NOT NULL ENABLE,
	"FUNCCODE" NUMBER NOT NULL ENABLE,
	"FUNCREV" NUMBER NOT NULL ENABLE,
	"DOCTID" NUMBER NOT NULL ENABLE,
	"FUNCNAME" VARCHAR2(100 BYTE),
	"FUNCDATE" DATE DEFAULT sysdate,
	"FUNCSTATUS" VARCHAR2(5 BYTE),
	"PIC1" VARCHAR2(15 BYTE),
	"PIC2" VARCHAR2(15 BYTE),
	"REMARK" VARCHAR2(255 BYTE)
   )