CREATE TABLE DS_CUSTOMER (
    CUS_ID INT(3) NOT NULL,
    CUS_NAME VARCHAR(10),
    CUS_DISPLAY VARCHAR(100),
    CUS_AGENT VARCHAR(5),
    CUS_COUNTRY VARCHAR(100),
    CUS_CURENCY VARCHAR(5),
    CUS_TERM VARCHAR(5),
    CUS_PROJECT_PREFIX VARCHAR(50),
    CUS_ADDRESS VARCHAR(250),
    CUS_CONTACT VARCHAR(100),
    CUS_EMAIL VARCHAR(150),
    CUS_QUOTATION INT(2),
    CUS_LT TINYINT(1),
    CUS_ADJUST DECIMAL(10,2)
);