

  CREATE TABLE "PRICELIST"
   (	"FYYEAR" NUMBER(4,0),
	"PERIOD" CHAR(1 BYTE),
	"ITEM" NUMBER,
	"STATUS" CHAR(1 BYTE),
	"STARTIN" VARCHAR2(22 BYTE),
	"INQUIRY" NUMBER,
	"FCCOST" NUMBER,
	"FCBASE" NUMBER,
	"TCCOST" NUMBER,
	"LATEST" CHAR(1 BYTE),
	"CREATE_AT" TIMESTAMP (6),
	"CREATE_BY" VARCHAR2(100 BYTE),
	"PRICEID" NUMBER ) ;
