CREATE TABLE PRICELIST (
    FYYEAR INT,
    PERIOD VARCHAR(255),
    ITEM INT,
    STATUS VARCHAR(255),
    STARTIN VARCHAR(255),
    INQUIRY INT,
    FCCOST DECIMAL(10,2),
    FCBASE DECIMAL(10,2),
    TCCOST DECIMAL(10,2),
    LATEST VARCHAR(255)
);