CREATE TABLE "PROGRAM_MSTLST"
   (	"DIVCODE" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"PROTID" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"PROMID" NUMBER NOT NULL ENABLE,
	"PROMNAME" VARCHAR2(50 BYTE),
	"PROMDESC" VARCHAR2(100 BYTE),
	"PIC" VARCHAR2(5 BYTE),
	"PIC2" VARCHAR2(5 BYTE),
	"PROMSTATUS" VARCHAR2(5 BYTE),
	"RELEASERS1" VARCHAR2(5 BYTE),
	"RELEASERS2" VARCHAR2(5 BYTE),
	"DATAOWNER" VARCHAR2(6 BYTE)
   )