--------------------------------------------------------
--  File created - Saturday-November-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FLOWMST
--------------------------------------------------------

  CREATE TABLE "WEBFORM"."FLOWMST" 
   (	"NFRMNO" NUMBER(3,0), 
	"VORGNO" VARCHAR2(6 BYTE), 
	"CYEAR" CHAR(2 BYTE), 
	"CSTEPNO" CHAR(2 BYTE), 
	"CSTEPNEXTNO" CHAR(2 BYTE), 
	"VPOSNO" VARCHAR2(3 BYTE), 
	"VAPVNO" VARCHAR2(12 BYTE), 
	"VAPVORGNO" VARCHAR2(6 BYTE), 
	"VURL" VARCHAR2(1024 BYTE), 
	"CSTART" CHAR(1 BYTE) DEFAULT '0', 
	"CTYPE" CHAR(1 BYTE), 
	"CEXTDATA" CHAR(2 BYTE), 
	"CAPVTYPE" CHAR(1 BYTE) DEFAULT '1', 
	"CREJTYPE" CHAR(1 BYTE) DEFAULT '1', 
	"CAPPLYALL" CHAR(1 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM" ;
  GRANT SELECT ON "WEBFORM"."FLOWMST" TO "WEBFORMTS";
--------------------------------------------------------
--  DDL for Index SYS_C0032109
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBFORM"."SYS_C0032109" ON "WEBFORM"."FLOWMST" ("NFRMNO", "VORGNO", "CYEAR", "CSTEPNO", "CSTEPNEXTNO", "VAPVNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM" ;
--------------------------------------------------------
--  Constraints for Table FLOWMST
--------------------------------------------------------

  ALTER TABLE "WEBFORM"."FLOWMST" ADD PRIMARY KEY ("NFRMNO", "VORGNO", "CYEAR", "CSTEPNO", "CSTEPNEXTNO", "VAPVNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FLOWMST
--------------------------------------------------------

  ALTER TABLE "WEBFORM"."FLOWMST" ADD FOREIGN KEY ("CSTEPNEXTNO")
	  REFERENCES "WEBFORM"."STEPMST" ("CNO") ENABLE;
  ALTER TABLE "WEBFORM"."FLOWMST" ADD FOREIGN KEY ("CSTEPNO")
	  REFERENCES "WEBFORM"."STEPMST" ("CNO") ENABLE;
  ALTER TABLE "WEBFORM"."FLOWMST" ADD FOREIGN KEY ("NFRMNO", "VORGNO", "CYEAR")
	  REFERENCES "WEBFORM"."FORMMST" ("NNO", "VORGNO", "CYEAR") ENABLE;
