--------------------------------------------------------
--  File created - Saturday-November-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FLOW
--------------------------------------------------------

  CREATE TABLE "WEBFORM"."FLOW" 
   (	"NFRMNO" NUMBER(3,0), 
	"VORGNO" VARCHAR2(6 BYTE), 
	"CYEAR" CHAR(2 BYTE), 
	"CYEAR2" CHAR(4 BYTE), 
	"NRUNNO" NUMBER(7,0), 
	"CSTEPNO" CHAR(2 BYTE), 
	"CSTEPNEXTNO" CHAR(2 BYTE), 
	"CSTART" CHAR(1 BYTE) DEFAULT '0', 
	"CSTEPST" CHAR(1 BYTE) DEFAULT ('1'), 
	"CTYPE" CHAR(1 BYTE), 
	"VPOSNO" VARCHAR2(5 BYTE), 
	"VAPVNO" VARCHAR2(12 BYTE), 
	"VREPNO" VARCHAR2(12 BYTE), 
	"VREALAPV" VARCHAR2(12 BYTE), 
	"CAPVSTNO" CHAR(1 BYTE), 
	"DAPVDATE" DATE, 
	"CAPVTIME" CHAR(8 BYTE), 
	"CEXTDATA" CHAR(2 BYTE), 
	"CAPVTYPE" CHAR(1 BYTE) DEFAULT '1', 
	"CREJTYPE" CHAR(1 BYTE) DEFAULT '1', 
	"CAPPLYALL" CHAR(1 BYTE) DEFAULT '0', 
	"VURL" VARCHAR2(1024 BYTE), 
	"VREMARK" VARCHAR2(4000 BYTE), 
	"VREMOTE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 6569984 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM"  ENABLE ROW MOVEMENT ;
  GRANT SELECT ON "WEBFORM"."FLOW" TO "GPREPORT";
  GRANT DELETE ON "WEBFORM"."FLOW" TO "GPREPORT";
  GRANT UPDATE ON "WEBFORM"."FLOW" TO "GPREPORT";
  GRANT ALTER ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT DELETE ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT INDEX ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT INSERT ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT SELECT ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT UPDATE ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT REFERENCES ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT ON COMMIT REFRESH ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT QUERY REWRITE ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT DEBUG ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT FLASHBACK ON "WEBFORM"."FLOW" TO "EBUDGET";
  GRANT SELECT ON "WEBFORM"."FLOW" TO "AMECKWL";
  GRANT DELETE ON "WEBFORM"."FLOW" TO "IEDOC";
  GRANT INSERT ON "WEBFORM"."FLOW" TO "IEDOC";
  GRANT SELECT ON "WEBFORM"."FLOW" TO "IEDOC";
  GRANT UPDATE ON "WEBFORM"."FLOW" TO "IEDOC";
  GRANT SELECT ON "WEBFORM"."FLOW" TO "WORKLOAD";
  GRANT UPDATE ON "WEBFORM"."FLOW" TO "WORKLOAD";
  GRANT SELECT ON "WEBFORM"."FLOW" TO "SMARTMAT";
  GRANT SELECT ON "WEBFORM"."FLOW" TO "DOCINV";
  GRANT DELETE ON "WEBFORM"."FLOW" TO "DOCINV";
  GRANT INSERT ON "WEBFORM"."FLOW" TO "DOCINV";
  GRANT UPDATE ON "WEBFORM"."FLOW" TO "DOCINV";
  GRANT SELECT ON "WEBFORM"."FLOW" TO "AMEC";
  GRANT SELECT ON "WEBFORM"."FLOW" TO "WEBFORMARCH";
--------------------------------------------------------
--  DDL for Index FLOW1_IND
--------------------------------------------------------

  CREATE INDEX "WEBFORM"."FLOW1_IND" ON "WEBFORM"."FLOW" ("NFRMNO", "VORGNO", "CYEAR", "CYEAR2", "NRUNNO", "VAPVNO", "CSTEPST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM" ;
--------------------------------------------------------
--  Constraints for Table FLOW
--------------------------------------------------------

  ALTER TABLE "WEBFORM"."FLOW" ADD PRIMARY KEY ("NFRMNO", "VORGNO", "CYEAR", "CYEAR2", "NRUNNO", "CSTEPNO", "CSTEPNEXTNO", "VAPVNO", "VREPNO") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table FLOW
--------------------------------------------------------

  ALTER TABLE "WEBFORM"."FLOW" ADD FOREIGN KEY ("NFRMNO", "VORGNO", "CYEAR", "CYEAR2", "NRUNNO")
	  REFERENCES "WEBFORM"."FORM" ("NFRMNO", "VORGNO", "CYEAR", "CYEAR2", "NRUNNO") ENABLE;
  ALTER TABLE "WEBFORM"."FLOW" ADD FOREIGN KEY ("CSTEPNO")
	  REFERENCES "WEBFORM"."STEPMST" ("CNO") ENABLE;
  ALTER TABLE "WEBFORM"."FLOW" ADD FOREIGN KEY ("CSTEPNEXTNO")
	  REFERENCES "WEBFORM"."STEPMST" ("CNO") ENABLE;
