--------------------------------------------------------
--  File created - Saturday-November-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FORMMST
--------------------------------------------------------

  CREATE TABLE "WEBFORM"."FORMMST" 
   (	"NNO" NUMBER(3,0), 
	"VORGNO" VARCHAR2(6 BYTE) DEFAULT '00', 
	"CYEAR" CHAR(2 BYTE), 
	"NRUNNO" NUMBER(4,0), 
	"VNAME" VARCHAR2(80 BYTE), 
	"VANAME" VARCHAR2(20 BYTE), 
	"VDESC" VARCHAR2(256 BYTE), 
	"DCREDATE" DATE, 
	"CCRETIME" CHAR(8 BYTE), 
	"VAUTHPAGE" VARCHAR2(1024 BYTE) DEFAULT null, 
	"VFORMPAGE" VARCHAR2(1024 BYTE) DEFAULT null, 
	"VDIR" VARCHAR2(255 BYTE), 
	"NLIFETIME" NUMBER(3,0) DEFAULT 6, 
	"CSTATUS" CHAR(1 BYTE) DEFAULT '2'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM" ;
  GRANT SELECT ON "WEBFORM"."FORMMST" TO "EBUDGET";
  GRANT SELECT ON "WEBFORM"."FORMMST" TO "SMARTMAT";
  GRANT SELECT ON "WEBFORM"."FORMMST" TO "AMECKWL";
  GRANT SELECT ON "WEBFORM"."FORMMST" TO "ISSTOCK";
  GRANT REFERENCES ON "WEBFORM"."FORMMST" TO "ISSTOCK";
  GRANT SELECT ON "WEBFORM"."FORMMST" TO "WEBFORMTS";
--------------------------------------------------------
--  DDL for Index SYS_C0031875
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBFORM"."SYS_C0031875" ON "WEBFORM"."FORMMST" ("NNO", "VORGNO", "CYEAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM" ;
--------------------------------------------------------
--  Constraints for Table FORMMST
--------------------------------------------------------

  ALTER TABLE "WEBFORM"."FORMMST" ADD PRIMARY KEY ("NNO", "VORGNO", "CYEAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORMMST
--------------------------------------------------------

  ALTER TABLE "WEBFORM"."FORMMST" ADD FOREIGN KEY ("CSTATUS")
	  REFERENCES "WEBFORM"."FORMMSTSTS" ("CNO") ENABLE;
