--------------------------------------------------------
--  File created - Saturday-November-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FORM
--------------------------------------------------------

  CREATE TABLE "WEBFORM"."FORM" 
   (	"NFRMNO" NUMBER(3,0), 
	"VORGNO" VARCHAR2(6 BYTE) DEFAULT '00', 
	"CYEAR" CHAR(2 BYTE), 
	"CYEAR2" CHAR(4 BYTE), 
	"NRUNNO" NUMBER(7,0), 
	"VREQNO" VARCHAR2(12 BYTE), 
	"VINPUTER" VARCHAR2(12 BYTE), 
	"VREMARK" VARCHAR2(4000 BYTE), 
	"DREQDATE" DATE, 
	"CREQTIME" CHAR(8 BYTE), 
	"CST" CHAR(1 BYTE) DEFAULT '0', 
	"VFORMPAGE" VARCHAR2(1024 BYTE), 
	"VREMOTE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1310720 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM"  ENABLE ROW MOVEMENT ;
  GRANT SELECT ON "WEBFORM"."FORM" TO "GPREPORT" WITH GRANT OPTION;
  GRANT DELETE ON "WEBFORM"."FORM" TO "GPREPORT";
  GRANT INSERT ON "WEBFORM"."FORM" TO "GPREPORT";
  GRANT UPDATE ON "WEBFORM"."FORM" TO "GPREPORT";
  GRANT ALTER ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT DELETE ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT INDEX ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT INSERT ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT SELECT ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT UPDATE ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT REFERENCES ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT ON COMMIT REFRESH ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT QUERY REWRITE ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT DEBUG ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT FLASHBACK ON "WEBFORM"."FORM" TO "EBUDGET";
  GRANT SELECT ON "WEBFORM"."FORM" TO "AMECKWL";
  GRANT SELECT ON "WEBFORM"."FORM" TO "DOCINV";
  GRANT SELECT ON "WEBFORM"."FORM" TO "IEDOC";
  GRANT DELETE ON "WEBFORM"."FORM" TO "IEDOC";
  GRANT INSERT ON "WEBFORM"."FORM" TO "IEDOC";
  GRANT UPDATE ON "WEBFORM"."FORM" TO "IEDOC";
  GRANT SELECT ON "WEBFORM"."FORM" TO "WORKLOAD";
  GRANT SELECT ON "WEBFORM"."FORM" TO "SMARTMAT";
  GRANT DELETE ON "WEBFORM"."FORM" TO "DOCINV";
  GRANT INSERT ON "WEBFORM"."FORM" TO "DOCINV";
  GRANT UPDATE ON "WEBFORM"."FORM" TO "DOCINV";
  GRANT SELECT ON "WEBFORM"."FORM" TO "AMEC";
  GRANT SELECT ON "WEBFORM"."FORM" TO "ISSTOCK" WITH GRANT OPTION;
  GRANT REFERENCES ON "WEBFORM"."FORM" TO "ISSTOCK" WITH GRANT OPTION;
  GRANT SELECT ON "WEBFORM"."FORM" TO "WEBFORMARCH";
--------------------------------------------------------
--  DDL for Index SYS_C0032110
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBFORM"."SYS_C0032110" ON "WEBFORM"."FORM" ("NFRMNO", "VORGNO", "CYEAR", "CYEAR2", "NRUNNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM" ;
--------------------------------------------------------
--  Constraints for Table FORM
--------------------------------------------------------

  ALTER TABLE "WEBFORM"."FORM" ADD PRIMARY KEY ("NFRMNO", "VORGNO", "CYEAR", "CYEAR2", "NRUNNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBFORM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORM
--------------------------------------------------------

  ALTER TABLE "WEBFORM"."FORM" ADD FOREIGN KEY ("NFRMNO", "VORGNO", "CYEAR")
	  REFERENCES "WEBFORM"."FORMMST" ("NNO", "VORGNO", "CYEAR") ENABLE;
