CREATE TABLE VALL_ITEMARRNGLST(
    ORDERNO VARCHAR(9),
    MELCALACLS VARCHAR(1),
    ITEMNO VARCHAR(3),
    SERIALNO VARCHAR(4),
    BMCLS VARCHAR(1),
    APNAMERMRK VARCHAR(50),
    PARTNO VARCHAR(50),
    TOTALQTY number,
    SCNDPRTCLS VARCHAR(20),
    SUPPLYCLS VARCHAR(20),
    REVSUBNO VARCHAR(20)
);