create table  DS_CUSTER_ITEM(
    CUSTOMER_ID NUMBER,
    ITEMS_ID  NUMBER,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR2(50),
    UPDATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR2(50),
);