CREATE TABLE JOB_EXECUTION_LOGS (
    ID VARCHAR(36) PRIMARY KEY,
    JOB_ID VARCHAR(36) NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME,
    DURATION_MS INT,
    STATUS VARCHAR(255),
    RESPONSE_CODE INT,
    OUTPUT_MESSAGE TEXT,
    INDEX idx_job_id (JOB_ID),
    FOREIGN KEY (JOB_ID) REFERENCES SCHEDULED_JOBS(ID)
);