CREATE TABLE SCHEDULED_JOBS (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    URL VARCHAR(512) NOT NULL,
    PARAMETES TEXT,
    CRON_EXPRESSION VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    IS_ACTIVE TINYINT(1) DEFAULT 1,
    LAST_RUN_AT DATETIME,
    INCHARGE VARCHAR(255),
    CREATE_BY VARCHAR(255),
    CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(255),
    UPDATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_name (NAME),
    INDEX idx_is_active (IS_ACTIVE),
    INDEX idx_last_run (LAST_RUN_AT)
);