create table AMECUSERALL(
    SEMPNO VARCHAR(5),
    SNAME VARCHAR(50),
    SRECMAIL VARCHAR(200),
    SSECCODE VARCHAR(50),
    SSEC VARCHAR(50),
    SDEPCODE VARCHAR(50),
    SDEPT VARCHAR(50),
    SDIVCODE VARCHAR(50),
    SDIV VARCHAR(50),
    SPOSCODE VARCHAR(50),
    SPOSNAME VARCHAR(50),
    SPASSWORD1 VARCHAR(50),
    CSTATUS VARCHAR(50),
    SEMPENCODE VARCHAR(50),
    MEMEML VARCHAR(50),
    STNAME VARCHAR(50)
)