create table SP_WEIGHT (
    INQ_ID	NUMBER,
    SEQ_WEIGHT	NUMBER,
    NO_WEIGHT	NUMBER,
    PACKAGE_TYPE	NVARCHAR2,
    NET_WEIGHT	NUMBER,
    GROSS_WEIGHT	NUMBER,
    WIDTH_WEIGHT	NUMBER,
    LENGTH_WEIGHT	NUMBER,
    HEIGHT_WEIGHT	NUMBER,
    VOLUMN_WEIGHT	NUMBER,
    ROUND_WEIGHT	NUMBER
);