CREATE TABLE WORK_STATUS (
    STATUS_ID INT NOT NULL,
    STATUS_ACTION VARCHAR(255),
    STATUS_DESC VARCHAR(255),
    STATUS_CLASS VARCHAR(255) NOT NULL,
    PRIMARY KEY (STATUS_ID, STATUS_CLASS)
);