
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "AMECMFG"."A_TABLE_CHECK" ("TB_LIBRARY", "TB_NAME", "TB_SOURCE", "TB_EXTRACT", "TB_STATUS", "ID", "CONDITION", "PIC", "REMARK", "KEY_COLUMN", "SOURCE_REC", "TARGET_REC", "TB_COLS", "SOURCE_CHECK", "TARGET_CHECK", "LAST_SYNC", "DEFAULTJRN", "TB_DATABASE", "SKIPCHECK", "GROUP_NAME", "SEQNO", "RBA", "AUDIT_TS", "LAST_UPDATE", "ROWNUMS", "SOURCECHECK", "TARGETCHECK") AS
  select A."TB_LIBRARY",A."TB_NAME",A."TB_SOURCE",A."TB_EXTRACT",A."TB_STATUS",A."ID",A."CONDITION",A."PIC",A."REMARK",A."KEY_COLUMN",A."SOURCE_REC",A."TARGET_REC",A."TB_COLS",A."SOURCE_CHECK",A."TARGET_CHECK",A."LAST_SYNC",A."DEFAULTJRN",A."TB_DATABASE",A."SKIPCHECK", B."GROUP_NAME",B."SEQNO",B."RBA",B."AUDIT_TS",B."LAST_UPDATE",B."ROWNUMS", TO_CHAR(A.SOURCE_CHECK, 'yyyy-mm-dd hh24:mi:ss') AS SOURCECHECK, TO_CHAR(A.TARGET_CHECK, 'yyyy-mm-dd hh24:mi:ss') AS TARGETCHECK
from A_TABLE_LIST A
left join A_TABLE_SYNC B on substr(TB_EXTRACT, 2, length(TB_EXTRACT)-2)||'A' = substr(GROUP_NAME, 2, length(GROUP_NAME)-1);

