
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "AMEC"."APP_LOG_VIEW" ("LOG_DATE", "LOG_TIME", "LOG_SERVER", "LOG_USER", "LOG_USERNAME", "LOG_DOMAIN", "LOG_HOST", "LOG_IP", "LOG_MSG", "LOG_LOGIN_STATUS") AS
  SELECT
to_char("DATETIME",'yyyy-mm-dd') AS LOG_DATE,
to_char("DATETIME",'HH24:MI:SS') AS LOG_TIME,
'WEBFLOW' AS LOG_SERVER,
A.SEMPNO AS LOG_USER,
B.SNAME AS LOG_USERNAME,
'Procurement' AS LOG_DOMAIN,
PC_NAME AS LOG_HOST,
IP AS LOG_IP,
CASE WHEN REASON IS NULL THEN  ' ' ELSE reason end AS LOG_MSG,
CASE LOGIN_FLAG WHEN '1' THEN 'Success' ELSE 'Fail' END AS  LOG_LOGIN_STATUS
FROM USRACCESSLOG A
JOIN AMECUSER B ON A.SEMPNO = B.SEMPNO
--WHERE SYSTEM_ACCESS = 'PROCUREMENT';