create table SP_ATTACHED(
    INQ_NO	VARCHAR,
    FILE_NAME	VARCHAR PRIMARY KEY,
    FILE_ORIGINAL_NAME	VARCHAR,
    FILE_SIZE	Int,
    FILE_TYPE	VARCHAR,
    FILE_CLASS	VARCHAR,
    FILE_STATUS	Int,
    FILE_OWNER	VARCHAR,
    FILE_MAR_READ	Int,
    FILE_DES_READ	Int,
    FILE_CREATE_AT	TIMESTAMP(6),
    FILE_CREATE_BY	VARCHAR
)