create table CUSTOMER (
    CUS_ID	INT,
    CUS_NAME	VARCHAR,
    CUS_DISPLAY	VARCHAR,
    CUS_AGENT	VARCHAR,
    CUS_COUNTRY	VARCHAR,
    CUS_CURENCY	VARCHAR,
    CUS_TERM	VARCHAR,
    CUS_PROJECT_PREFIX	VARCHAR,
    CUS_ADDRESS	VARCHAR,
    CUS_CONTACT	VARCHAR,
    CUS_EMAIL	VARCHAR,
    CUS_QUOTATION	INT,
    CUS_LT	INT,
    CUS_ADJUST	INT,
    Primary key(CUS_ID)
);