CREATE TABLE "SPSYS"."DS_CUSTOMER"
   (	"CUS_ID" NUMBER(3,0) NOT NULL ENABLE,
	"CUS_NAME" NVARCHAR2(10),
	"CUS_DISPLAY" NVARCHAR2(100),
	"CUS_AGENT" NVARCHAR2(5),
	"CUS_COUNTRY" NVARCHAR2(100),
	"CUS_CURENCY" NVARCHAR2(5),
	"CUS_TERM" NVARCHAR2(5),
	"CUS_PROJECT_PREFIX" NVARCHAR2(50),
	"CUS_ADDRESS" NVARCHAR2(250),
	"CUS_CONTACT" NVARCHAR2(100),
	"CUS_EMAIL" NVARCHAR2(150),
	"CUS_QUOTATION" NUMBER(2,0),
	"CUS_LT" NUMBER(1,0),
	"CUS_ADJUST" NUMBER
   )