  CREATE OR REPLACE FORCE EDITIONABLE VIEW "AMEC"."DB_LOGIN_VIEW" ("LOGON_DAY", "LOGON_TIME", "USER_DB", "PC_NAME", "IP_ADDRESS", "PROGRAM1") AS
  SELECT
LOGON_DAY, LOGON_TIME, USER_DB, PC_NAME , IP_ADDRESS,PROGRAM1
FROM	sys.user_log
UNPIVOT	(
	    (LOGON_DAY, LOGON_TIME,PROGRAM1)  FOR col_label IN
            (
                (LOGON_DAY,LOGON_TIME, PROGRAM)	AS 1
	    	    , (LOGOFF_DAY,LOGOFF_TIME, PROGRAM) AS 2
			)
	)
WHERE USER_DB IN ('AMEC', 'DEV02', 'SYS','SYSDBA', 'SYSMAN', 'SYSTEM')
AND PC_NAME  NOT IN ('AMECWEB1', 'AMECWEB2');