CREATE TABLE "DOCLIST_MST"
   (	"DOCTID" NUMBER(5,0) NOT NULL ENABLE,
	"DOCTNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"STATUS" VARCHAR2(3 BYTE),
	"CREATE_URL" VARCHAR2(500 BYTE),
	"SEQ" NUMBER(2,0)
   )