create table SP_INQUIRY_LOG (
    LOG_DATE TIMESTAMP,
    INQD_ID	INT(10),
    INQD_SEQ	FLOAT(5,2),
    INQD_RUNNO	INT(5),
    INQD_MFGORDER	VARCHAR(50),
    INQD_ITEM	VARCHAR(10),
    INQD_CAR	VARCHAR(50),
    INQD_PARTNAME	VARCHAR(200),
    INQD_DRAWING	VARCHAR(200),
    INQD_VARIABLE	VARCHAR(255),
    INQD_QTY	INT(10,3),
    INQD_UM	VARCHAR(10),
    INQD_SUPPLIER	VARCHAR(25),
    INQD_SENDPART	INT(1),
    INQD_UNREPLY	INT(2),
    INQD_FC_COST	FLOAT(11,4),
    INQD_TC_COST	FLOAT(11,4),
    INQD_UNIT_PRICE	FLOAT(11,4),
    INQD_FC_BASE	FLOAT(7,4),
    INQD_TC_BASE	FLOAT(7,4),
    INQD_MAR_REMARK	VARCHAR(3000),
    INQD_DES_REMARK	VARCHAR(1000),
    INQD_FIN_REMARK	VARCHAR(1000),
    CREATE_AT	TIMESTAMP,
    CREATE_BY	VARCHAR(100),
    UPDATE_AT	TIMESTAMP,
    UPDATE_BY	VARCHAR(100),
    primary key (LOG_DATE)
);


CREATE OR REPLACE TRIGGER SP_CHANGE_LOG
AFTER UPDATE OF INQD_CAR,INQD_DRAWING,INQD_FC_COST,INQD_FIN_REMARK,INQD_MAR_REMARK,INQD_MFGORDER,INQD_PARTNAME,INQD_QTY,INQD_SENDPART,INQD_SEQ,INQD_SUPPLIER,INQD_TC_COST,INQD_UNIT_PRICE,INQD_UNREPLY,INQD_VARIABLE,INQD_DES_REMARK,INQD_UM OR DELETE ON SP_INQUIRY_DETAIL
FOR EACH ROW
BEGIN
  INSERT INTO SP_INQUIRY_LOG (
INQD_ID, INQD_SEQ, INQD_RUNNO, INQD_MFGORDER, INQD_ITEM, INQD_CAR, INQD_PARTNAME, INQD_DRAWING, INQD_VARIABLE, INQD_QTY, INQD_UM, INQD_SUPPLIER, INQD_SENDPART, INQD_UNREPLY, INQD_FC_COST, INQD_TC_COST, INQD_UNIT_PRICE, INQD_FC_BASE, INQD_TC_BASE, INQD_MAR_REMARK, INQD_DES_REMARK, INQD_FIN_REMARK, UPDATE_AT, UPDATE_BY
) VALUES (:OLD.INQD_ID, :OLD.INQD_SEQ, :OLD.INQD_RUNNO, :OLD.INQD_MFGORDER, :OLD.INQD_ITEM, :OLD.INQD_CAR, :OLD.INQD_PARTNAME, :OLD.INQD_DRAWING, :OLD.INQD_VARIABLE, :OLD.INQD_QTY, :OLD.INQD_UM, :OLD.INQD_SUPPLIER, :OLD.INQD_SENDPART, :OLD.INQD_UNREPLY, :OLD.INQD_FC_COST, :OLD.INQD_TC_COST, :OLD.INQD_UNIT_PRICE, :OLD.INQD_FC_BASE, :OLD.INQD_TC_BASE, :OLD.INQD_MAR_REMARK, :OLD.INQD_DES_REMARK, :OLD.INQD_FIN_REMARK, :OLD.UPDATE_AT, :OLD.UPDATE_BY);
END;