create table SP_INQUIRY_LOG (
    LOG_DATE TIMESTAMP DETAULT SYSDATE,
    INQD_ID	NUMBER(10,0),
    INQD_SEQ	NUMBER(5,2),
    INQD_RUNNO	NUMBER(5,0),
    INQD_MFGORDER	VARCHAR2(50 BYTE),
    INQD_ITEM	VARCHAR2(10 BYTE),
    INQD_CAR	VARCHAR2(50 BYTE),
    INQD_PARTNAME	VARCHAR2(200 BYTE),
    INQD_DRAWING	VARCHAR2(200 BYTE),
    INQD_VARIABLE	VARCHAR2(255 BYTE),
    INQD_QTY	NUMBER(10,3),
    INQD_UM	VARCHAR2(10 BYTE),
    INQD_SUPPLIER	VARCHAR2(25 BYTE),
    INQD_SENDPART	NUMBER(1,0),
    INQD_UNREPLY	NUMBER(2,0),
    INQD_FC_COST	NUMBER(11,4),
    INQD_TC_COST	NUMBER(11,4),
    INQD_UNIT_PRICE	NUMBER(11,4),
    INQD_FC_BASE	NUMBER(7,4),
    INQD_TC_BASE	NUMBER(7,4),
    INQD_MAR_REMARK	VARCHAR2(3000 BYTE),
    INQD_DES_REMARK	VARCHAR2(1000 BYTE),
    INQD_FIN_REMARK	VARCHAR2(1000 BYTE),
    CREATE_AT	TIMESTAMP(6),
    CREATE_BY	VARCHAR2(100 BYTE),
    UPDATE_AT	TIMESTAMP(6),
    UPDATE_BY	VARCHAR2(100 BYTE),
    primary key (LOG_DATE)
);


CREATE OR REPLACE TRIGGER SP_CHANGE_LOG
AFTER UPDATE OF INQD_CAR,INQD_DRAWING,INQD_FC_COST,INQD_FIN_REMARK,INQD_MAR_REMARK,INQD_MFGORDER,INQD_PARTNAME,INQD_QTY,INQD_SENDPART,INQD_SEQ,INQD_SUPPLIER,INQD_TC_COST,INQD_UNIT_PRICE,INQD_UNREPLY,INQD_VARIABLE,INQD_DES_REMARK,INQD_UM OR DELETE ON SP_INQUIRY_DETAIL
FOR EACH ROW
BEGIN
  INSERT INTO SP_INQUIRY_LOG (
INQD_ID, INQD_SEQ, INQD_RUNNO, INQD_MFGORDER, INQD_ITEM, INQD_CAR, INQD_PARTNAME, INQD_DRAWING, INQD_VARIABLE, INQD_QTY, INQD_UM, INQD_SUPPLIER, INQD_SENDPART, INQD_UNREPLY, INQD_FC_COST, INQD_TC_COST, INQD_UNIT_PRICE, INQD_FC_BASE, INQD_TC_BASE, INQD_MAR_REMARK, INQD_DES_REMARK, INQD_FIN_REMARK, UPDATE_AT, UPDATE_BY
) VALUES (:OLD.INQD_ID, :OLD.INQD_SEQ, :OLD.INQD_RUNNO, :OLD.INQD_MFGORDER, :OLD.INQD_ITEM, :OLD.INQD_CAR, :OLD.INQD_PARTNAME, :OLD.INQD_DRAWING, :OLD.INQD_VARIABLE, :OLD.INQD_QTY, :OLD.INQD_UM, :OLD.INQD_SUPPLIER, :OLD.INQD_SENDPART, :OLD.INQD_UNREPLY, :OLD.INQD_FC_COST, :OLD.INQD_TC_COST, :OLD.INQD_UNIT_PRICE, :OLD.INQD_FC_BASE, :OLD.INQD_TC_BASE, :OLD.INQD_MAR_REMARK, :OLD.INQD_DES_REMARK, :OLD.INQD_FIN_REMARK, :OLD.UPDATE_AT, :OLD.UPDATE_BY);
END;