CREATE TABLE PROGRAM_MODULE (
  PROGRAM int DEFAULT NULL,
  MODULE_ID int DEFAULT NULL,
  MODULE_NAME varchar(120) DEFAULT NULL,
  MODULE_CREATE date DEFAULT NULL,
  MODULE_PIC varchar(5) DEFAULT NULL
)