create or replace PROCEDURE EMP_DEV_UPDATE(
  IN_EMPCOD IN VARCHAR2,
  IN_EMPDEP IN VARCHAR2,
  IN_EMPPOS IN VARCHAR2
) AS
    v_count NUMBER;
    v_div NUMBER;
    v_dep NUMBER;
    v_sec NUMBER;
    v_pos NUMBER;
    v_flag NUMBER;
    v_pass  VARCHAR2(50);
    divcode VARCHAR2(6);
    depcode VARCHAR2(6);
    seccode VARCHAR2(6);
    sname VARCHAR2(120);
    stname VARCHAR2(120);
    resign NUMBER;
BEGIN
    divcode := CASE WHEN SUBSTR(IN_EMPDEP, 3, 4) = '0101' THEN IN_EMPDEP ELSE SUBSTR(IN_EMPDEP, 1, 2) || '0101' END;
    depcode := CASE WHEN SUBSTR(IN_EMPDEP, 3, 4) = '0101' THEN '00' WHEN SUBSTR(IN_EMPDEP, 5, 2) != '01' THEN SUBSTR(IN_EMPDEP, 0, 4)||'01' ELSE IN_EMPDEP END;
    seccode := CASE WHEN SUBSTR(IN_EMPDEP, 5, 2) != '01' THEN IN_EMPDEP ELSE '00' END;

    SELECT COUNT(*) INTO v_div from AMEC.PDIVISION@WEBFLOWDB WHERE SDIVCODE = divcode;
    IF v_div = 0 THEN
        INSERT INTO AMEC.PDIVISION@WEBFLOWDB(SDIVCODE) VALUES(divcode);
    END IF;

    SELECT COUNT(*) INTO v_dep from AMEC.PDEPARTMENT@WEBFLOWDB WHERE SDEPCODE = depcode;
    IF v_dep = 0 THEN
        INSERT INTO AMEC.PDEPARTMENT@WEBFLOWDB(SDEPCODE) VALUES(depcode);
    END IF;

    SELECT COUNT(*) INTO v_sec from AMEC.PSECTION@WEBFLOWDB WHERE SSECCODE = seccode;
    IF v_sec = 0 THEN
        INSERT INTO AMEC.PSECTION@WEBFLOWDB(SSECCODE) VALUES(seccode);
    END IF;

    SELECT COUNT(*) INTO v_pos from AMEC.PPOSITION@WEBFLOWDB WHERE SPOSCODE = IN_EMPPOS;
    IF v_pos = 0 THEN
        INSERT INTO AMEC.PPOSITION@WEBFLOWDB(SPOSCODE) VALUES(IN_EMPPOS);
    END IF;

    SELECT EMPNME, EMPNMT, EMPRDT INTO sname, stname, resign FROM MHMEMP00 WHERE EMPCOD = IN_EMPCOD;
    UPDATE AMEC.AEMPLOYEE@WEBFLOWDB SET
        SPOSCODE = IN_EMPPOS,
        SDIVCODE = divcode,
        SDEPCODE = depcode,
        SSECCODE = seccode,
        SNAME = sname,
        STNAME = stname
    WHERE SEMPNO = IN_EMPCOD;

    UPDATE ORGPOS@WEBFLOWDB
    SET VPOSNO = IN_EMPPOS, VORGNO = IN_EMPDEP
    WHERE VEMPNO = IN_EMPCOD;

    DELETE FROM USRAUTH@WEBFLOWDB WHERE VEMPNO = IN_EMPCOD;
    INSERT INTO USRAUTH@WEBFLOWDB
    SELECT  EMPCOD, NNO, VORGNO, CYEAR, '001' FROM FORMMST@WEBFLOWDB, (SELECT IN_EMPCOD AS EMPCOD FROM DUAL) WHERE CSTATUS = '1';

    IF divcode = '060101' THEN
        DELETE FROM USRAUTH@WEBFLOWDB WHERE NFRMNO = 11 AND VORGNO = '030101' AND CYEAR = '08' AND VEMPNO = IN_EMPCOD;
    ELSE
        DELETE FROM USRAUTH@WEBFLOWDB WHERE NFRMNO = 2 AND VORGNO = '030101' AND CYEAR = '09' AND VEMPNO = IN_EMPCOD;
    END IF;

    IF IN_EMPPOS < 50 THEN
        DELETE FROM USRAUTH@WEBFLOWDB WHERE NFRMNO = 2 AND VORGNO = '030101' AND CYEAR = '08' AND VEMPNO = IN_EMPCOD;
    END IF;

    IF IN_EMPPOS > 30 THEN
        DELETE FROM USRAUTH@WEBFLOWDB WHERE NFRMNO IN ('5','6','7','8') AND VORGNO = '030101' AND CYEAR = '08' AND VEMPNO = IN_EMPCOD;
        DELETE FROM USRAUTH@WEBFLOWDB WHERE NFRMNO =1 AND VORGNO = '030101' AND CYEAR IN ('04','12') AND VEMPNO = IN_EMPCOD;
    END IF;


    IF(resign > 0) THEN
        SELECT count(*) INTO v_flag FROM EMPLOYEE_LOG WHERE SEMPNO = IN_EMPCOD AND FLAG = 'D';
        IF v_flag = 0 THEN
            INSERT INTO EMPLOYEE_LOG (SEMPNO, SDIVCODE, SDEPCODE, SSECCODE, SPOSCODE, SNAME, STNAME, RESIGNDATE, BRANCH, ACNUMBER, CSTATUS, FLAG, LASTUPDATE)
            SELECT EMPCOD, SDIVCODE, SDEPCODE, SSECCODE, EMPPOS, EMPNME, EMPNMT, TO_DATE(EMPRDT, 'yyyymmdd'),  substr('000'||EMPBNC, -3), EMPACN,  0, 'D', TO_DATE(EMPRDT, 'yyyymmdd')
            FROM MHMEMP00  , (SELECT divcode SDIVCODE, depcode SDEPCODE, seccode SSECCODE, v_pass AS PASS from dual)
            WHERE EMPCOD = IN_EMPCOD;
        END IF;
    ELSE
        INSERT INTO EMPLOYEE_LOG (SEMPNO, SDIVCODE, SDEPCODE, SSECCODE, SPOSCODE, SNAME, STNAME, RESIGNDATE, BRANCH, ACNUMBER, CSTATUS, FLAG, LASTUPDATE)
        SELECT EMPCOD, SDIVCODE, SDEPCODE, SSECCODE, EMPPOS, EMPNME, EMPNMT, null,  substr('000'||EMPBNC, -3), EMPACN,  1, 'U', SYSDATE
        FROM MHMEMP00  , (SELECT divcode SDIVCODE, depcode SDEPCODE, seccode SSECCODE, v_pass AS PASS from dual)
        WHERE EMPCOD = IN_EMPCOD;
    END IF;
END;