CREATE TABLE PROGRAM (
  PGM_ID int DEFAULT NULL,
  PGM_CODE varchar(20) DEFAULT NULL,
  PGM_NAME varchar(120) DEFAULT NULL,
  PGM_DESC varchar(200) DEFAULT NULL,
  PGM_OWNER varchar(10) DEFAULT NULL,
  PGM_TYPE varchar(1) DEFAULT NULL
);