Create table SP_QUOTATION(
    QUO_ID	NUMBER,
    QUO_INQ	NUMBER,
    QUO_REV	VARCHAR2,
    QUO_DATE	DATE,
    QUO_VALIDITY	DATE,
    QUO_PIC	VARCHAR2,
    QUO_SEA_FREIGHT	NUMBER,
    QUO_SEA_VOLUMN	NUMBER,
    QUO_SEA_TOTAL	NUMBER,
    QUO_AIR_FREIGHT	NUMBER,
    QUO_AIR_VOLUMN	NUMBER,
    QUO_AIR_TOTAL	NUMBER,
    QUO_COURIER_FREIGHT	NUMBER,
    QUO_COURIER_VOLUMN	NUMBER,
    QUO_COURIER_TOTAL	NUMBER,
    QUO_NOTE	VARCHAR2,
    QUO_LATEST	NUMBER
);